<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Using the multiDA to classify cancer types - a case study • multiDA</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Using the multiDA to classify cancer types - a case study">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">multiDA</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">1.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/multiDAvignette_caseStudy.html">Using the multiDA to classify cancer types - a case study</a>
    </li>
    <li>
      <a href="../articles/multiDA_vignette_themodel.html">What does multiDA actually do?</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Using the multiDA to classify cancer types - a case study</h1>
            
      
      
      <div class="hidden name"><code>multiDAvignette_caseStudy.Rmd</code></div>

    </div>

    
    
<p>One particular type of data that is well suited for use by multiDA is microarray data. In this example, we demostrate the power of multiDA in predicting cancer type using the provided <code>SRBCT</code> data.</p>
<div id="small-round-blue-cell-tumors-srbct-data" class="section level1">
<h1 class="hasAnchor">
<a href="#small-round-blue-cell-tumors-srbct-data" class="anchor"></a>Small Round Blue Cell Tumors (SRBCT) data</h1>
<p>The SRBCT dataset (Khan, 2001) looks at classifying <strong>4 classes</strong> of different childhood tumours sharing similar visual features during routine histology. These classes include Ewing’s family of tumours (EWS), neuroblastoma (NB), Burkitt’s lymphoma (BL), and rhabdomyosarcoma (RMS). Data was collected from 63 cDNA microarrays, with 1586 features present after filtering for genes with zero median absolute deviation. The data can be accessed by typing <code>SRBCT</code>. We assign our feature data to <code>X</code>, and our response data to <code>y</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">library</span>(multiDA)</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="kw">summary</span>(SRBCT)</a></code></pre></div>
<pre><code>##   Length Class  Mode   
## X 99918  -none- numeric
## y    63  factor numeric</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">X &lt;-<span class="st"> </span>SRBCT<span class="op">$</span>X</a>
<a class="sourceLine" id="cb3-2" title="2">y &lt;-<span class="st"> </span>SRBCT<span class="op">$</span>y</a></code></pre></div>
</div>
<div id="fitting-the-multida-model-to-the-srbct-data" class="section level1">
<h1 class="hasAnchor">
<a href="#fitting-the-multida-model-to-the-srbct-data" class="anchor"></a>Fitting the multiDA model to the SRBCT data</h1>
<p>We will fit a multiDA model to describe the group structure for each feature.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1">res  &lt;-<span class="st"> </span><span class="kw"><a href="../reference/multiDA.html">multiDA</a></span>(<span class="dt">X=</span>X, <span class="dt">y=</span>y, <span class="dt">penalty=</span><span class="st">"EBIC"</span>, <span class="dt">equal.var=</span><span class="ot">TRUE</span>, <span class="dt">set.options=</span><span class="st">"exhaustive"</span>)</a></code></pre></div>
<ul>
<li>We use the default <code>EBIC</code> penalty as we have much more features than observations.</li>
<li>We use the option <code>equal.var = TRUE</code> to fit a model which assumes each Gaussian curve has the same variance.</li>
<li>The option <code>set.options = "exhaustive"</code> tells the multiDA algorithm to consider all 15 options of grouping 4 objects together (see <em>What does multiDA actually do?</em> <a href="https://sarahromanes.github.io/multiDA/articles/multiDA_vignette_themodel.html">here</a> for describing possible group structures). If the number of classes is much larger, say 5 or 6, the number of groupings grows rapidly (see Bell Number <a href="https://en.wikipedia.org/wiki/Bell_number">here</a>), and so another set option may be considered to restrict the number of groupings explored.</li>
</ul>
<p>We can explore the results of the multiDA model using the <code>print()</code> function:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">print</span>(res)</a></code></pre></div>
<pre><code>## Sample Size:
## [1] 63
## Number of Features:
## [1] 1586
## Classes:
## [1] 4
## Equal Variance Assumption:
## [1] TRUE
## Number of Significant Features:
## [1] 215
## Summary of Significant Features:
##    rank feature.ID gamma.hat partition
## 1     1      V1172 0.9997741         8
## 2     2      V1232 0.9997576         4
## 3     3      V1233 0.9997563         3
## 4     4      V1324 0.9997506         3
## 5     5       V706 0.9997441         5
## 6     6       V434 0.9997437         3
## 7     7       V527 0.9997424         3
## 8     8      V1189 0.9997368         3
## 9     9      V1166 0.9997347         7
## 10   10       V148 0.9997342         4
## Partition Matrix:
## [1] "exhaustive"
##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
## [1,]    1    1    1    1    1    1    1    1    1     1     1     1     1
## [2,]    1    1    1    2    2    2    1    2    2     1     2     2     2
## [3,]    1    2    1    1    2    2    2    1    3     2     1     3     2
## [4,]    1    1    2    1    2    1    2    2    1     3     3     2     3
##      [,14] [,15]
## [1,]     1     1
## [2,]     2     2
## [3,]     3     3
## [4,]     3     4</code></pre>
<p>The key information returned to us is that 215 of the 1586 are deemed significant, with high <code>gamma.hat</code> values inndicating a higher probablity of membership to a particular partitioning. For example, for the most significant feature V1172, there is a 0.999 chance that it is described by partition 8, which, looking at the Partition Matrix output, consists of classes 1 and 3 described by a Gaussian curve, and classes 2 and 4 explained by a Gaussian curve (2 cueves altogether).</p>
<p>A low top value of <code>gamma.hat</code> indicates high uncertainty in model fit even for the most significant features - and in such a case another ML algorithm should be considered.</p>
</div>
<div id="exploring-the-plot-functionality" class="section level1">
<h1 class="hasAnchor">
<a href="#exploring-the-plot-functionality" class="anchor"></a>Exploring the plot functionality</h1>
<p>We can visualise the paritioning of the classes within each feature using the <code>plot()</code> method for multiDA. By default, the plot function plots the top 10 ranked features. If `ranked=FALSE, then the user can specify which features to be plotted (specified by column names).</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw">plot</span>(res, <span class="dt">ranks =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="multiDAvignette_caseStudy_files/figure-html/unnamed-chunk-4-1.png" width="700"></p>
<p>An example using specified features:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="kw">plot</span>(res, <span class="dt">ranked=</span><span class="ot">FALSE</span>, <span class="dt">features =</span> <span class="kw">c</span>(<span class="st">"V22"</span>))</a></code></pre></div>
<p><img src="multiDAvignette_caseStudy_files/figure-html/unnamed-chunk-5-1.png" width="700"></p>
</div>
<div id="prediction-using-the-multida-algorithm" class="section level1">
<h1 class="hasAnchor">
<a href="#prediction-using-the-multida-algorithm" class="anchor"></a>Prediction using the multiDA algorithm</h1>
<p>If we want to predict class labels, we can use the <code>predict</code> function in order to do so. In this case, we will find the resubstitution error rate for this dataset using the multiDA algorithm. We can either extract the probability of class membership for each point (<code>$probabilities</code>) or we can directly extract class membership prediction (which class had the max probability) using <code>$y.pred</code>.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1">prediction &lt;-<span class="st"> </span><span class="kw">predict</span>(res, <span class="dt">newdata=</span>X)</a>
<a class="sourceLine" id="cb9-2" title="2"></a>
<a class="sourceLine" id="cb9-3" title="3"><span class="kw">head</span>(prediction<span class="op">$</span>probabilities)</a></code></pre></div>
<pre><code>##               [,1] [,2]          [,3]         [,4]
## [1,] 1.908807e-135    1  1.336194e-99 2.596398e-68
## [2,] 1.214488e-123    1  3.550677e-80 8.116775e-55
## [3,] 1.530691e-162    1 3.396422e-123 8.374009e-63
## [4,] 1.601513e-108    1  3.320017e-67 3.077376e-35
## [5,] 1.860622e-157    1 7.604828e-114 4.035431e-64
## [6,] 1.469110e-171    1 5.841163e-129 1.691079e-80</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="kw">head</span>(prediction<span class="op">$</span>y.pred)</a></code></pre></div>
<pre><code>## [1] 2 2 2 2 2 2
## Levels: 1 2 3 4</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">vals &lt;-<span class="st"> </span>prediction<span class="op">$</span>y.pred </a>
<a class="sourceLine" id="cb13-2" title="2">rser &lt;-<span class="st"> </span><span class="kw">sum</span>(vals<span class="op">!=</span>y)<span class="op">/</span><span class="kw">length</span>(y)</a>
<a class="sourceLine" id="cb13-3" title="3">rser</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
</div>
<div id="using-the-multida-tidy-functions" class="section level1">
<h1 class="hasAnchor">
<a href="#using-the-multida-tidy-functions" class="anchor"></a>Using the multiDA “tidy” functions</h1>
<p>Tidy functions have been created for ease of use - namely <code><a href="../reference/multiDA.broom.html">glimpse_multiDA()</a></code> and <code><a href="../reference/multiDA.broom.html">tidy_multiDA()</a></code>, both of which take a trained multiDA object (in this case, <code>res</code>) as function input.</p>
<div id="multida-glimpse-function" class="section level3">
<h3 class="hasAnchor">
<a href="#multida-glimpse-function" class="anchor"></a>multiDA “glimpse” function</h3>
<p>This function returns a one row data frame, with quick summaries from the algorithm. In the spirit of the “glance” function from the <code>broom</code> package.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw"><a href="../reference/multiDA.broom.html">glimpse_multiDA</a></span>(res)</a></code></pre></div>
<pre><code>##   Classes Number.of.Partitions Number.of.Signficant.Features Top.Gamma
## 1       4                   15                          1586 0.9997741</code></pre>
</div>
<div id="multida-tidy-function" class="section level3">
<h3 class="hasAnchor">
<a href="#multida-tidy-function" class="anchor"></a>multiDA “tidy” function</h3>
<p>This returns a tidy data frame, with key results from the trained multiDA object, namely, a <code>data.frame</code> of significant features and their ranks. In the spirit of “tidy” from the <code>broom</code> package.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1">tidy_res &lt;-<span class="st"> </span><span class="kw"><a href="../reference/multiDA.broom.html">tidy_multiDA</a></span>(res)</a>
<a class="sourceLine" id="cb17-2" title="2"><span class="kw">head</span>(tidy_res)</a></code></pre></div>
<pre><code>##   rank feature.ID gamma.hat partition
## 1    1      V1172 0.9997741         8
## 2    2      V1232 0.9997576         4
## 3    3      V1233 0.9997563         3
## 4    4      V1324 0.9997506         3
## 5    5       V706 0.9997441         5
## 6    6       V434 0.9997437         3</code></pre>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#small-round-blue-cell-tumors-srbct-data">Small Round Blue Cell Tumors (SRBCT) data</a></li>
      <li><a href="#fitting-the-multida-model-to-the-srbct-data">Fitting the multiDA model to the SRBCT data</a></li>
      <li><a href="#exploring-the-plot-functionality">Exploring the plot functionality</a></li>
      <li><a href="#prediction-using-the-multida-algorithm">Prediction using the multiDA algorithm</a></li>
      <li><a href="#using-the-multida-tidy-functions">Using the multiDA “tidy” functions</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Sarah Romanes.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
